### ISSUE TITLE
weekly check-ins’ record - 1st, 2nd, 3rd release

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#24]
Every week you can expect 3 comments: 
- an AGENDA for the coming standup meeting
- a short update with urgent todo’s and recap from the meeting
- a log with updates on what happened during the week

**Comment by 0xjona** [comment]
AGENDA for 5.24 meeting
- new github project format (+ labels)
- meeting with PL PMs for best practices
- checklist for graphic design (+ creating issues)
- braistorming about “how-to-use” documentation 
- working on milestones (Work-breakdown-structure and Critical-Path-Method tools)

**Comment by irenegia** [comment]
TODOs
- [ ] @irene set a chat for Jona woth PMs
- [ ] @0xjona open the graphic design issues and set the first call
- [ ] @0xjona create a unique issue about documentation

**Comment by 0xjona** [comment]
### WEEKLY UPDATE 27.5
_What happened_
Initiated the workflow (with check-ins and public updates)
Deals are now NFTs, meaning providers can transfer them
Moving to PL servers 80% done (MVP is offline)
Started breaking down some issues (also related to protocol research with cryptoecon team)

_What to expect next week_ 
Improved readme on github (and improvements to the general documentation)
Official Links for the mvp and etherscan
Working on naming (product design first step)
Smart contract audit

**Comment by 0xjona** [comment]
### AGENDA for 5.31 check-in
- [ ] talking about feasability of issue #2
- [ ] updating the use of issues and milestones
- [ ] discussing deliverables for next sprint
- [ ] what do we need to freeze the protocol? When audit?
- [ ] breakdown issue #30

Today we also start working on #26

**Comment by irenegia** [comment]
> updating the use of issues and milestones

- we may want to use zenhub for timeline (jona), detailed on a period of 2 weeks
- organize the work in order to have monthly 

> discussing deliverables for next sprint
- due date for milestone 1: 23rd july
  - we need to divide milestone 1 in 2 releases  
  - 1st release (due date: 24th june): 
    - smart contract freeze 
    - website is live 
    - light paper
  - 2nd release (due date: 23rd july):
    - audit
    - frontend improvements 
    - monitoring tools

**Comment by 0xjona** [comment]
ToDo
- [ ] async discussion about #2 _team_
- [ ] agree and specify #35 _team_
- [x] start #34 @0xjona 
- [ ] update README to include expected releases @0xjona 
- [ ] create EPIC for #30 @0xjona 

_team_ @turinglabsorg @Steve-Rog @irenegia @claudiofabbro

**Comment by 0xjona** [comment]
### AGENDA for 6.7 check-in

- [ ] talk about #10 to define and validate
- [ ] #30 what issues will be in 1st release and how we produce the content?
- [ ] each issue should have a due date (and a milestone)
- [ ] comments on naming
- [ ] comments on reputation score
- [ ] comments on 1st release (which new issues are involved) and envisioning 2nd release

**Comment by 0xjona** [comment]
###TODOs

- [ ] comment each issue we talked about with updates and analysis or content requests from author/client
- [ ] we need #10 feedbacks to close the issue and move forward
- [ ] we need to close #26 or at least agree on a first iteration
- [ ] discussione about new NFT proposal for #2

**Comment by 0xjona** [comment]
### UPDATES 06.10
Hi everyone!

We are moving forward with development and are coming to terms about how to name the product.

- We are validating the already committed NFT improvement (join discussion here https://github.com/protocol/retriev/issues/10#issuecomment-1152394250 )
- We’ve designed and developed the wireframe for the homepage 
- We’ve upgraded the front-end of the MVP (see https://pldr.dev )
- We added admin functions to fine tune the protocol values
- We’re close to define the formula for the “reputation score mechanism” (check https://github.com/protocol/retriev/issues/2#issuecomment-1152380376 ) 
- We are doing tests to the code of the smart contract, also to check the gas fees (collecting and comparing results to other dapps)

**Comment by 0xjona** [comment]
### AGENDA 14.6
- [ ] in tomorrow’s check-in we’ll talk about
- [ ] naming (strong dependencies)
- [ ] foundry tests first results
- [ ] smart contract parameter (both for reputation score and economics) 
- [ ] wireframe
- [ ] NFTs & metadata

**Comment by irenegia** [comment]
**Notes from the call:**


> * [x]  naming (strong dependencies)

 more proposals! We will discuss these on slack! 
> * [x]  foundry tests first results

see the update in the issue #44 
> * [ ]  smart contract parameter (both for reputation score and economics)

scheduled an had-hoc call for wed
> * [x]  wireframe

https://pldr.dev/#/. wow!!! :) 
 - contributors to add in the team section
 - link slack channel to add

**Comment by 0xjona** [comment]
ToDo
- [ ] discuss the NFTs metadata/render
- [ ] organize the demo day for end of June

**Comment by 0xjona** [comment]
#### UPDATE 
- foundry tests live and done https://github.com/protocol/retriev/issues/44
- API deployed https://github.com/protocol/retriev/issues/14
- Results of the CryptoEcon review will be included in the litepaper https://github.com/protocol/retriev/issues/39
- we have live notifications https://github.com/protocol/retriev/issues/3

**Comment by 0xjona** [comment]
UPDATE 6.24
Hi everyone!
Next week we’ll have a first release for Retrieval-pinning (looks like we have a new name :party:) with a demo introducing to key features and a brand new design!

Recent fixes and updates from the development
- API https://github.com/protocol/retriev/issues/14https://github.com/protocol/retriev/issues/14
- Docker support https://github.com/protocol/retriev/issues/5
- Security assessment with Slither
- Provider UI https://github.com/protocol/retriev/issues/4

**Comment by 0xjona** [comment]
### AGENDA
- [ ] check issues in _validation_
- [ ] check #35 
- [ ] talk about #48 (what we have, what is missing)
- [ ] start envisioning next steps (2nd release and milestone 2) [timeline in presentation]
- [ ] which issues we are discussing about and which ones are _future upgrades_

**Comment by 0xjona** [comment]
Hi everyone!
Our website is live at pldr.dev and you can launch the dApp.pldr.dev 🚀🚀

This week we finalised the demo for this month of work, making improvements and new features!
We’ll share the video recorded by @irene asap!

Still we are constantly making fixes https://github.com/protocol/retriev/issues/43 (and 

https://github.com/protocol/retriev/issues/54)

And we are starting discussions on new features to be developed in the following weeks!

**Comment by 0xjona** [comment]
AGENDA 5 JULY
We’ll start working heading toward a 2ns release for Milestone 1 at the end of July!

Tomorrow we’ll talk about:
- [ ] 1st release feedbacks (also how to collect them)
- [ ] 2nd release EPIC
- [ ] Issues to do breakdown (planning both brainstorming and estimate implementation)
- [ ] Open issues, how to deal with

**Comment by 0xjona** [comment]
### UPDATE @nicola
Goal: Usable product that can be used to convince NFT.Storage to use it

What to do next

- Provider software upgrades
  * Retrieves file via IPFS, check size and price, then confirm
  * Pricing strategy (low priority)
  * Make sure that pricing can be free (payment, collateral, etc)
  
- Protocol upgrades
  * Add appeal key to deal, which is an array of addresses enabled to run the createAppeal function.
  * Place on-chain limit on on-going appeals
  * (Separation of protocols)

- Testing
  * Auto dealer
  * Bad node / Good node (we already have it)
  * Test parallel appeals

- Website
  * Main page
  * Actual app

**Comment by 0xjona** [comment]
AGENDA tomorrow meeting 
- Freezing release 2 
- “bird eye view” next months / where to find consensus?
- Discussing the diagram https://pl-strflt.notion.site/Retrievability-Consortium-Demo-9255b4e292d8478faae764593fa8bad2  that we need to agree to design the UX
- ALPHA UX https://github.com/protocol/retriev/issues/29#issuecomment-1180730250 

In detail: 
2nd release 
- appeal key (client side field) e admin key (for random checks)
- Provider CLI (signup onchain via CLI - how to manage automatic“accept deal” policies aka price*kilobyte*time)
- Appeal on-chain limit (discussion about appeal time stamp)

**Comment by 0xjona** [comment]
### notes from call 
@nicola @irenegia 
 


**Action items:**
- Give access to Jona and Sebastiano to the feedback that we will get from the rest of PL
- Make a plan for receiving internal feedback
  - Create a program for early storage providers
  - Identify early group of people that can give feedback (users, applications and storage providers)
- Provider CLI will pin on local node by default, then provider can stop pinning by running a simple command like `pin disable`
- Clients CLI (new) to create deals and make appeals directly with terminal and local file system
- Check if we can use cloudflare IPFS to temporary cache files or try using ipfs-js to run a node on the browser and checks if provider can reach browser node
- Multi-referee network: Add a settings page where you can choose the referee contract, question: api? We must add contract and api endpoint (new referee network will provide to users) or provide legacy support to referee networks
- Add button with referees network on top of the UI where we show the addresses of the referees and some other protocol parameters
- Add Terms of Service when create new deal proposal, a recap of contract parameters, referee network etc.

**dApp feedbacks:**

_Bugfix:_
- Collateral NaN when string is empty
- Collateral in expert mode starts from 0, not payment

_Improvements:_
- Basic mode: deal duration and payment must be buttons like metamask gas
- Expert mode: add more than one appeal addresses with a + that creates new inputs

**Comment by turinglabsorg** [comment]
> Collateral NaN when string is empty
> Collateral in expert mode starts from 0, not payment

both fixed in local, will push the updates later today

**Comment by 0xjona** [comment]
### AGENDA for tomorrow's check-in
- [ ] new visuals and UI for onchain storage app
- [ ] #15 brainstorm
- [ ] detailing onboarding strategy
- [ ] #7 

when _retro_? @nicola

**Comment by 0xjona** [comment]
**meta points**
make things usable as fast as possible (and show impact)
so that we quickly understand what’s best to do
(becoming aware of what we don’t like)
→ good to build product, but we need to build products people use

**process**
→ set of retrieval nodes ecc vs soft lunch (we are the nodes)
comfortable with change
as you do change make sure there are intermediate milestone that allow this software to make impact
(files on filecoin with 0 collateral)

**fix**
no nice homepage
abstract domain
better plan to evaluate impact on this tool 

**past**
retrieval service only
specific deals for retrieval service
we want to make other products
making sure the product has more complex features
opportunity to generalize the “retrieval pinning” product

**present**
ecosystem storage product
having other developers contributing
→ what kind of products?  https://cryptonet.org/projects/on-chain-storage-products 
[multiple version of this very same products]
onchain storage is the place to have experience and explore this products
giving people the opportunity to “”

market for storage products
check pricing, services, and buying

same protocols can be used by other UXs
for each service/protocol there’s a webpage stating “here you can try/use/buy this service” + list

retrieval pinning introduces you to the protocol features (specs for des)
and maybe also which platforms are using it (several storage providers e oracles ecc)
and maybe having a demo online

onchain.storage is an aggregator and links to other webpages where you can go deeper into understanding protocols

see zapper / zerion 

storage products can be made by other teams
each protocol might have s light brand identity (recognizable)
some of this products might have their network (oracle) and tokens
onchain storage combines this deals and takes a fee 

**options**
final user doesn’t get to see infra
different reputation systems can be then aggregated
on choosing a providers →  “which reputation system you want to use”
good defaults but customisable
to minimise the number of onchain request, we could have one call to smartcontrat?

onchain storage is UX for protocols
(nicola feels like something about what he’s envisioning is wrong, we gotta get what it is)
we can’t over commit on things we’ll have to change

come up with a plan for brand strategy (and we’ll discuss it)

**features**
make PR and you’ll see the many protocol updating

my dashboard vs marketplace + deal making tool

for protocols
website and readme are for experts
form super customisable
→ you need to have experience to get things (clients have)

useful for
small files they want to upload
find deal per website vs website hosting (recepits)
(deal making tool for custom deals)

**comments**
where do we need to find mass adoption?
we can guide those who’ll come after onchain.storage
if the whole community works, each user will benefit

**summary per agreement share**
write down notes and ideas
talk very often
change what we’ve written
let’s choose what to keep and what to leave
we must have visual clues to see what we’re talking about
and eventually calibrate time of resources/team

**Comment by 0xjona** [comment]
- create internal docs for coordination, high level directions
  - working map (epic)
  - what the product will look like?
- focus on product usability (better “ugly” bust stable, than too many stuff that are confusing)
  - we need to understand if people want this! “survival mode”
  - how to prove we generate impact ??
  - retrieval pinning and NFT.storage need to be usable!

**three lines:**
1) product side (nicola, jona), websites etc
   - what are this products we need to ship
   - timeline
2) finish protocols (luca, irene)
3) adoption

**goals**

- [ ] - make sure all the protocol exists (secure, safe)
- [ ] - make sure we have something nice and launchable by end october


**metrics for impact:**
- step 1: client can use this to store NFT/data on filecoin/ NFT.storage (and web3.storage)
- step 2: how to integrate those contracts into other contracts (make a deal with nft.storage while minting an nft)

_what are the things we need to show at events?_


**create documentation and use cases for onchain.storage (Seb)**
