### ISSUE TITLE
Documentation (EPIC)

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#30]
We need to discuss together what kind of documentation we need to develop and why.
After this brainstorming phase, we’ll have to breakdown this issue into further steps.

As for the issues we were having, do we still need
- [x] video guides to explain the product or give public updates (blog posts, presentations)
- [ ] ~public documentation wiki, built using gitbook or similar OSS~
- [x] convert notion documentation to a lite paper
- [x] write down the read me how to run the demo (github /install)

In this issue me and @irenegia will define the deliverables, which will be planned accordingly (e.g. writing down the lite paper assigned to irene and design a visual guide outsourced to graphic designer)

### UPDATE
- [ ] #37 
- [x] #38
- [x] #39
- [x] #40

**Comment by 0xjona** [comment]
@irenegia should we set a call? Who else should be involved?

**Comment by irenegia** [comment]
@0xjona 
I believe we can briefly discuss this in the next weekly call as the list you wrote is basically already complete.
Just few comments:

>  video guides to explain the product or give public updates (blog posts, presentations)

I would reduce the scope of this: 1 blog post and 1 video (demo of 5 minutes)

> write down the read me how to run the demo (github /install)

perfect!

> convert notion documentation to a lite paper

perfect! 

> public documentation wiki, built using gitbook or similar OSS

since we have the lite paper with a complete description of the protocol (theory part) and we have the 'read me' as installation guide (practical part), I suggest to remove this. 
We just need some simple text explain the protocol at high level to fill the web site, once we have it.

**Comment by 0xjona** [comment]
we need the "about"

**Comment by 0xjona** [comment]
We just need a little improvement in website homepage copy (will come after internal feedbacks and brainstorm) and work on the #37 for #62
