### ISSUE TITLE
Demo day (EPIC)

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#48]
We’ll have scheduled **Demo days** showcasing not just a collection of regular updates but a coordinated effort toward a designed release!

We are still deciding what this will consist of (videos, presentations, live walkthroughs ecc) but we need to coordinate to organise this small _event_

- [x] #35 expected in late June
- [x] #62 expected early august
- [ ] #71 expected late september

**Comment by nicola** [comment]
A recorded presentation showing the walk through (either live or screenshot) from the client side, the referee and the provider. The presentation should also present the project in high level in the first few slides and link to places where conversations can continue (e.g. slack, email, github etc).

**Comment by irenegia** [comment]
@nicola should we also plan already now a call with Juan and others for feedbacks?

**Comment by irenegia** [comment]
@0xjona 
I sent you some technical slides, beyond that let me know how can I help with the demo!

**Comment by 0xjona** [comment]
here's the demo for #62 https://filecoinproject.slack.com/archives/C03CJKWP2DR/p1659716456586289
