### ISSUE TITLE
2nd Release (EPIC)

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#62]
### UPDATED checklist for _2nd release_ expected on July 29 via a #48 with videos and presentation, to be found at last comment below!
I keep this old description to track changes

~**Identity**~
~- [ ] #27 to be finalised from @claudiofabbro, with icons, diagrams and sandbox/toolkit to present the project~

~**News**~
~- [ ] #37 together with @irenegia we’ll write content~
~- [ ] #57 @claudiofabbro and @Steve-Rog will design & implement this section on our website using https://contents.mego.cx~

~**Reputation score**~
~- [ ] #58~ 

~**dApp & contract**~
~- [ ] #7 @irenegia will find who’ll make the audit~
~- [ ] #53 @turinglabsorg will stress test the product~
~- [ ] #56 we’ll work on a draft to discuss this new feature~
~- [ ] #29 we’ll have propositions from @claudiofabbro and we’ll discuss them~
~- [ ] #43 @Steve-Rog will keep fixing and improving the MVP~

~**Parameters**~ 
~- [ ] #50 @irenegia~ 
~- [ ] #51 @turinglabsorg~

**Comment by irenegia** [comment]
Given what we discussed on wed in the planning/feedback call with @nicola (see #24 , I suggest we modify the checklist in:

**Identity**
- [ ] #27 to be finalised from @claudiofabbro, with icons, diagrams and sandbox/toolkit to present the project
  - [ ] [new] P0 to main page 

**News**
- [ ] #37 together with @irenegia we’ll write content
- [ ] ~#57 @claudiofabbro and @Steve-Rog will design & implement this section on our website using https://contents.mego.cx~ [postponed to sept]

~**Reputation score**~
- ~[ ] #58~ [postponed to sept]

**dApp & contract**
- [ ] #7 @irenegia will find who’ll make the audit
- [ ] #53 @turinglabsorg will stress test the product
  - [ ] auto dealer
  - [ ] bad/good node
  - [ ] parallel appeal
- [ ] #56 we’ll work on a draft to discuss this new feature
  - [ ] [new] provider software updates:retrieve file via IPFS, check size and price, then confirm (make sure payment can be 0)  
- [ ] #29 we’ll have propositions from @claudiofabbro and we’ll discuss them
- [ ] #43 @Steve-Rog will keep fixing and improving the MVP ("actual app")
- [ ] [new] appeal key #59 
- [ ] [new] limit on-chain on-going appeals/modify the protocol to create the appeal queue (require different starting time for the appeal process)

**Parameters** 
- [ ] #50 @irenegia 
- [ ] #51 @turinglabsorg

**Comment by 0xjona** [comment]
### UPDATED checklist for _2nd release_ expected on July 29 via a #48 with videos and presentation

**Identity** 
- [ ] #69 will complete the identity and will upgrade the #28 and provide #39 with visuals

**News**
- [ ] #37 together with @irenegia we’ll write content
~- [ ] #57 @claudiofabbro and @Steve-Rog will design & implement this section on our website using https://contents.mego.cx~ [postponed to sept]

**dApp & contract**
- [ ] #7 @irenegia will find who’ll make the audit
- [ ] #53 @turinglabsorg will stress test the product
  - [ ] auto dealer
  - [ ] bad/good node
  - [ ] parallel appeal
- [ ] #67 we are improving the CLI of the provider  
- [ ] #29 design of the UX of the client side of the ALPHA, following discussions at #64 
_We are discussing a Providers’ dashboard, to be designed and implemented in a 3rd release_ 
- [ ] #43 @Steve-Rog will keep fixing and improving the MVP ("actual app")
- [ ] #63 is designed to help queuing appeals 
- [ ] #65 defines the appeal addresses

**Parameters** 
- [ ] #50 @irenegia 
- [ ] #51 @turinglabsorg 

This changes might affect the provided documentation, so please @irene consider updating the #39 

—-

**mid-term vision**
@irene @nicola we’ll have to update the copy of the website #40, and register another domain to better specify the context.
