### ISSUE TITLE
3rd release (EPIC)

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#71]
This issue tracks work for the 3rd release; we have 3 main lines of work and we expect to ship the first iteration by the end of September.

We are working at
- [x] [P1] protocol/retrieval-pinning#81 --> oracle
- [ ] [P0] protocol/retrieval-pinning#82 
- [x] [P1] protocol/onchain-storage#1 

we have already developed
 - protocol/retrieval-pinning#80 
 - protocol/retrieval-pinning#79 
 - protocol/retrieval-pinning#77 
 - protocol/retrieval-pinning#76 
 - protocol/retrieval-pinning#75 
 - #85 
 - #72 
 - #69 

bonus
- #46 @claudiofabbro (once we've opted for a visual direction)

We are also planning to do protocol/retrieval-pinning#7 asap ( @irenegia )

**Comment by 0xjona** [comment]
- [ ] multi-referee network
- [ ] onchain.storage pivot (generic interface for pinning / UX research)
- [ ] desing _early storage providers and referees_ program
- [ ] FVM?

**Comment by irenegia** [comment]
-  onchain.storage pivot
   - Action items [next week]:
      - website: jona and claudio first proposal on new homepage (figma draft) + retrieval pinning homepage redesign
      - app: jona and claudio first proposal on new user ui (figma draft)
   - Next steps: feedback collations and impl

-  storage providers and referees program:
   -  Action items [next week]:  
       -  (1) @luca and @irenegia write down the list of calls to do with Jona (goal: find partners)
       -  (2) drafting interest form (see the FVM one)
   -  Next steps: form divulgation, user onboarding
   
- FVM and multi-referee network for now is just in a brainstorming phase for the possible design
   -  Action item [next week]: open issues to discuss these items

**Comment by 0xjona** [comment]
notes collected from feedbacks and discussione about things to implement
- [ ] #15 
- [ ] onchain database vs api https://github.com/turinglabsorg/ipdb 
- [ ] If someone wants to allow us to check them they add us as an appeal key (suggest this via UX)
- [ ] add multiple appeal addressese (+ other improvements already pointed out in the figma)
